### ISSUE TITLE
Socialite Provider Accounts erstellen

### ISSUE THREAD

**Issue by Pfannkuchensack** [oklabflensburg/open-trees-map#7]
Um Socialite für alle Provider (Apple, Microsoft/Github, Facebook, Google) nutzen zu können, brauchen wir einen Account bei den jeweiligen Providern. App/Webseite muss dann bei allen einmal erstellt werden und die Keys müssen in die .env auf dem Produktiv System.

[ Apple Besonderheit](https://bannister.me/blog/generating-a-client-secret-for-sign-in-with-apple-on-each-request)

**Comment by p3t3r67x0** [comment]
@Pfannkuchensack hattest du da noch weiter gemacht mit den social providern?

**Comment by Pfannkuchensack** [comment]
Ich habe bisher nix dazu gemacht, allerdings braucht es für die Laravel Geschichte auch nur Accounts bei den Anbietern. Software Seitig ist das alles sowas "fertig"
